name: Compile Kernel
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps: 

    - name: Setup environment
      run: |
        sudo add-apt-repository 'deb http://mirrors.kernel.org/ubuntu kinetic main universe'
        sudo apt-get update
        sudo apt-get install gcc-11 -y
        sudo apt-get upgrade libstdc++6 -y