# This is a basic workflow to help you get started with Actions

name: Compile Kernel
on:
  watch:
    types: [started]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Setup Build Environment
        run: |
          sudo add-apt-repository 'deb http://mirrors.kernel.org/ubuntu kinetic main universe'
          sudo apt-get update
          sudo apt-get install gcc-11 -y
          sudo apt-get upgrade libstdc++6 -y
